# Generated by Django 4.2.30 on 2026-06-04 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Mô tả cơ bản')),
                ('default_language', models.CharField(choices=[('python', 'Python 3'), ('cpp', 'C++ (GDB)')], default='python', max_length=20, verbose_name='Ngôn ngữ mặc định')),
                ('favorite_theme', models.CharField(choices=[('dark', 'Giao diện Tối'), ('light', 'Giao diện Sáng')], default='dark', max_length=20, verbose_name='Theme yêu thích')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
