# Generated by Django 5.0.6 on 2026-06-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(db_index=True, max_length=8, unique=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('author_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Author IP')),
                ('title', models.CharField(default='Không tên', max_length=100)),
                ('is_public', models.BooleanField(default=True)),
                ('language', models.CharField(max_length=20)),
                ('file_path', models.CharField(max_length=255)),
                ('input_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP Address')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Mô tả cơ bản')),
                ('default_language', models.CharField(choices=[('python', 'Python 3'), ('cpp', 'C++ (GDB)')], default='python', max_length=20, verbose_name='Ngôn ngữ mặc định')),
                ('favorite_theme', models.CharField(choices=[('dark', 'Giao diện Tối'), ('light', 'Giao diện Sáng')], default='dark', max_length=20, verbose_name='Theme UI yêu thích')),
                ('editor_theme', models.CharField(choices=[('unicorns-dark', 'Uni Dark'), ('unicorns-light', 'Uni Light'), ('vs-dark', 'VS Dark'), ('vs', 'VS Light'), ('hc-black', 'High Contrast Dark')], default='unicorns-dark', max_length=20, verbose_name='Theme Editor')),
                ('editor_font_family', models.CharField(choices=[("'Consolas', 'Fira Code', monospace", 'Consolas / Fira Code'), ("'JetBrains Mono', monospace", 'JetBrains Mono'), ("'Courier New', Courier, monospace", 'Courier New'), ("'Source Code Pro', monospace", 'Source Code Pro')], default="'Consolas', 'Fira Code', monospace", max_length=100, verbose_name='Font Editor')),
                ('editor_font_size', models.IntegerField(default=14, verbose_name='Cỡ chữ Editor')),
            ],
        ),
        migrations.CreateModel(
            name='CodeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_ip', models.GenericIPAddressField(verbose_name='Author IP')),
                ('name', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('all', 'All')], max_length=20)),
                ('code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('author_ip', 'name', 'language')},
            },
        ),
    ]
