# Generated by Django 5.0.6 on 2026-06-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='editor_font_family',
            field=models.CharField(choices=[("'Consolas', 'Fira Code', monospace", 'Consolas / Fira Code'), ("'JetBrains Mono', monospace", 'JetBrains Mono'), ("'Courier New', Courier, monospace", 'Courier New'), ("'Source Code Pro', monospace", 'Source Code Pro')], default="'Consolas', 'Fira Code', monospace", max_length=100, verbose_name='Font Editor'),
        ),
        migrations.AddField(
            model_name='profile',
            name='editor_font_size',
            field=models.IntegerField(default=14, verbose_name='Cỡ chữ Editor'),
        ),
        migrations.AddField(
            model_name='profile',
            name='editor_theme',
            field=models.CharField(choices=[('unicorns-dark', 'Unicorns Dark'), ('unicorns-light', 'Unicorns Light'), ('vs-dark', 'VS Dark'), ('vs', 'VS Light'), ('hc-black', 'High Contrast Dark')], default='unicorns-dark', max_length=20, verbose_name='Theme Editor'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_theme',
            field=models.CharField(choices=[('dark', 'Giao diện Tối'), ('light', 'Giao diện Sáng')], default='dark', max_length=20, verbose_name='Theme UI yêu thích'),
        ),
    ]
