# Generated by Django 5.0.6 on 2026-06-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_keymaptemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(default='Mage__', max_length=50, verbose_name='Tên tác giả'),
        ),
    ]
