# Generated by Django 5.0.6 on 2026-06-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0003_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Tên tác giả'),
        ),
    ]
