# Generated by Django 5.0.6 on 2026-06-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0003_codesnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
