# Generated by Django 5.0.6 on 2026-06-15 12:25

import compiler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0004_alter_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(default=compiler.models.generate_random_uni_name, max_length=50, verbose_name='Tên tác giả'),
        ),
    ]
