# Generated by Django 5.0.6 on 2026-06-15 13:33

import uuid
from django.db import migrations, models

def generate_unique_session_ids(apps, schema_editor):
    Profile = apps.get_model('compiler', 'Profile')
    for profile in Profile.objects.all():
        profile.session_id = uuid.uuid4().hex
        profile.save()
        
    CodeTemplate = apps.get_model('compiler', 'CodeTemplate')
    for template in CodeTemplate.objects.all():
        template.session_id = uuid.uuid4().hex
        template.save()

class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0005_alter_profile_display_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='codetemplate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Session ID'),
        ),
        migrations.AddField(
            model_name='codetemplate',
            name='session_id',
            field=models.CharField(max_length=100, null=True, verbose_name='Session ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='session_id',
            field=models.CharField(max_length=100, null=True, verbose_name='Session ID'),
        ),
        migrations.RunPython(generate_unique_session_ids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='codetemplate',
            name='session_id',
            field=models.CharField(max_length=100, verbose_name='Session ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='session_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Session ID'),
        ),
        migrations.AlterUniqueTogether(
            name='codetemplate',
            unique_together={('session_id', 'name', 'language')},
        ),
        migrations.RemoveField(
            model_name='codesnippet',
            name='author_ip',
        ),
        migrations.RemoveField(
            model_name='codetemplate',
            name='author_ip',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ip_address',
        ),
    ]
