# Generated by Django 4.2.30 on 2026-06-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0005_codetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='title',
            field=models.CharField(default='Không tên', max_length=100),
        ),
    ]
