# Generated by Django 5.0.6 on 2026-06-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0005_alter_profile_display_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='codetemplate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Session ID'),
        ),
        migrations.AddField(
            model_name='codetemplate',
            name='session_id',
            field=models.CharField(default='default_session', max_length=100, verbose_name='Session ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='session_id',
            field=models.CharField(default='default_session', max_length=100, unique=True, verbose_name='Session ID'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='codetemplate',
            unique_together={('session_id', 'name', 'language')},
        ),
        migrations.RemoveField(
            model_name='codesnippet',
            name='author_ip',
        ),
        migrations.RemoveField(
            model_name='codetemplate',
            name='author_ip',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ip_address',
        ),
    ]
